services:
  ##APP_NAME##:
    image: chdotworld/dotworld:base-alpine
    container_name: ##APP_NAME##
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - '${APP_VOLUME}:/workspaces/${APP_NAME}'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - infrastructure
networks:
  infrastructure:
    driver: bridge