#!/usr/bin/env bash

if [ ! -d /.composer ]; then
    mkdir /.composer
fi
chmod -R ugo+rw /.composer
chmod 666 /var/run/docker.sock

echo Container started && trap 'exit 0' 15 && while sleep 1 & wait $!; do :; done
