#!/usr/bin/env sh
set -eu

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer || true

: "${SERVER_NAME:=localhost, :80, :443}"

exec frankenphp run --server-name "$SERVER_NAME"

