services:
  ##APP_NAME##:
    image: chdotworld/dotworld:base-alpine
    container_name: ##APP_NAME##
    volumes:
      - '${APP_VOLUME}:/workspaces/${APP_NAME}'
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: sh -c "echo Container started && trap 'exit 0' 15 && while sleep 1 & wait $!; do :; done" 
