services:
  ##APP_NAME##:
    image: chdotworld/dotworld:php81-alpine
    container_name: ##APP_NAME##
    ports:
      - '${APP_PORT:-80}:80'
      - '${APP_WEBSOCKETS_PORT:-6001}:6001'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
    volumes:
      - '${APP_VOLUME}:/workspaces/${APP_NAME}'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - infrastructure
    depends_on:
      - ##APP_NAME##_redis
      - ##APP_NAME##_mysql
  ##APP_NAME##_mysql:
    image: mysql/mysql-server:8.0
    container_name: ##APP_NAME##_mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - '##APP_NAME##_mysql_data:/var/lib/mysql'
    networks:
      - infrastructure
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  ##APP_NAME##_redis:
    image: 'redis:alpine'
    container_name: ##APP_NAME##_redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - '##APP_NAME##_redis_data:/data'
    networks:
      - infrastructure
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
networks:
  infrastructure:
    driver: bridge

volumes:
  ##APP_NAME##_redis_data:
    driver: local
  ##APP_NAME##_mysql_data:
    driver: local
