services:
  ##APP_NAME##:
    image: chdotworld/dotworld:golang-air-atlas-ubuntu

    container_name: ##APP_NAME##
    volumes:
      - "${VOLUME_SESSIONKEEPER}:/workspaces/##APP_NAME##"
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - ##APP_NAME##_network
    depends_on:
      - ##APP_NAME##_clickhouse_server
      - ##APP_NAME##_redis
    ports:
      - '${AIR_PORT:-9090}:9090'

  ##APP_NAME##_redis:
    image: 'redis:alpine'
    container_name: ##APP_NAME##_redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - '##APP_NAME##_redis_data:/data'
    restart: unless-stopped
    networks:
      - ##APP_NAME##_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

  ##APP_NAME##_clickhouse_server:
    image: clickhouse/clickhouse-server
    container_name: ##APP_NAME##_clickhouse_server
    environment:
      CLICKHOUSE_DB: '${CLICKHOUSE_DB:-sessionkeeper}'
      CLICKHOUSE_USER: '${CLICKHOUSE_USER:-sessionkeeper}'
      CLICKHOUSE_PASSWORD: '${CLICKHOUSE_PASSWORD:-secret}'
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - '${FORWARD_CLICKHOUSE_HTTP_PORT:-8123}:8123'
      - '${FORWARD_CLICKHOUSE_NATIVE_PORT:-9000}:9000'
    volumes:
      - ##APP_NAME##_clickhouse_data:/var/lib/clickhouse
      - ./data/logs:/var/log
      - ./config/clickhouse/users.xml:/etc/clickhouse-server/users.xml
    networks:
      - ##APP_NAME##_network

networks:
  ##APP_NAME##_network:
    driver: bridge

volumes:
  ##APP_NAME##_redis_data:
    driver: local
  ##APP_NAME##_clickhouse_data:
    driver: local