services:
  air:
    image: 'cosmtrek/air:latest'
    ports:
      - '${AIR_PORT:-9090}:9090'
    volumes:
      - "${VOLUME_SESSIONKEEPER}:/app"
    working_dir: /app
    networks:
      - session_keeper
    depends_on:
      - clickhouse_server
      - redis

  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "${VOLUME_SESSIONKEEPER}:/app"
    networks:
      - session_keeper
    depends_on:
      - clickhouse_server
      - redis

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'session_keeper_redis_data:/data'
    restart: unless-stopped
    networks:
      - session_keeper
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

  clickhouse_server:
    image: clickhouse/clickhouse-server
    environment:
      CLICKHOUSE_DB: '${CLICKHOUSE_DB:-sessionkeeper}'
      CLICKHOUSE_USER: '${CLICKHOUSE_USER:-sessionkeeper}'
      CLICKHOUSE_PASSWORD: '${CLICKHOUSE_PASSWORD:-secret}'
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - '${FORWARD_CLICKHOUSE_HTTP_PORT:-8123}:8123'
      - '${FORWARD_CLICKHOUSE_NATIVE_PORT:-9000}:9000'
    volumes:
      - session_keeper_clickhouse_data:/var/lib/clickhouse
      - ./data/logs:/var/log
      - ./config/clickhouse/users.xml:/etc/clickhouse-server/users.xml
    networks:
      - session_keeper

  npm:
    image: node:alpine
    volumes:
      - '${VOLUME_SESSIONKEEPER}:/app'
    working_dir: /app
    networks:
      - session_keeper

networks:
  session_keeper:
    driver: bridge

volumes:
  session_keeper_redis_data:
    driver: local
  session_keeper_clickhouse_data:
    driver: local